name: Compatibility Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean install -DskipTests
      - name: Upload JAR artifacts
        uses: actions/upload-artifact@v4
        with:
          name: databend-jdbc-jars
          path: |
            databend-jdbc/target/*.jar
          retention-days: 1

  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: false
      matrix:
        server:
          - "nightly"
          - "v1.2.790-nightly"
    steps:
      - uses: actions/checkout@v4

      - name: Download JAR artifacts
        uses: actions/download-artifact@v4
        with:
          name: databend-jdbc-jars
          path: databend-jdbc/target/

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }} # Value of the GPG private key to import
          gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase

      - name: Start Cluster With Nginx and Minio
        working-directory: tests
        run: make up
        env:
          DATABEND_QUERY_VERSION: ${{ matrix.server }}


      - name: Test with conn to nginx
        working-directory: tests/compatibility
        run: sh test_compatibility.sh
        env:
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          DATABEND_TEST_CONN_PORT: 8000
          DATABEND_QUERY_VERSION: ${{ matrix.server }}
          TEST_SIDE: "driver"
